apiVersion: v1
kind: Template
metadata:
  name: result-api-buildconfig
  annotations:
    description: >
      This is Thoth Result API BuildConfig, this template is meant to be used by
      Bots, but could also be used by humans...
    openshift.io/display-name: "Thoth Result API BuildConfig"
    version: 0.7.1
    tags: thoth,result-api,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Thoth Result API BuildConfig, this template is meant to be used
      by Bots, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: result-api-buildconfig
    app: thoth
    component: result-api

parameters:
  - description: Name of the github repository for Thoth's Result API
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: "https://github.com/thoth-station/result-api"

  - description: Git reference to be used for Thoth's Result API
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: "master"

  - description: Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

  - description: Thamos Advise setup tag value
    displayName: THOTH_ADVISE
    required: true
    name: THOTH_ADVISE
    value: "1"

objects:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: result-api
      annotations:
        thoth-station.ninja/template-version: 0.7.1
      labels:
        app: thoth
        component: result-api
    spec:
      resources:
        limits:
          cpu: 2
          memory: 768Mi
        requests:
          cpu: 2
          memory: 768Mi
      output:
        to:
          kind: ImageStreamTag
          name: "result-api:${IMAGE_STREAM_TAG}"
      source:
        type: Git
        git:
          uri: "${GITHUB_URL}"
          ref: "${GITHUB_REF}"
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: s2i-thoth-ubi8-py36:latest
          env:
            - name: ENABLE_PIPENV
              value: "1"
            - name: UPGRADE_PIP_TO_LATEST
              value: ""
            - name: WEB_CONCURRENCY
              value: "4"
            - name: "THOTH_DRY_RUN"
              value: "0"
            - name: "THOTH_ADVISE"
              value: ${THOTH_ADVISE}
            - name: "THAMOS_VERBOSE"
              value: "1"
            - name: "THAMOS_DEBUG"
              value: "1"
            - name: "THAMOS_CONFIG_TEMPLATE"
              value: ".thoth.yaml"
            - name: "THAMOS_CONFIG_EXPAND_ENV"
              value: "1"
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
        - type: Generic
          generic:
            secretReference:
              name: generic-webhook-secret

  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        thoth-station.ninja/template-version: 0.7.1
      labels:
        app: thoth
      name: result-api
    spec:
      name: latest
